[theme]
base                     = "dark"
primaryColor             = "#00FF87"
backgroundColor          = "#0B0E13"
secondaryBackgroundColor = "#1B2130"
textColor                = "#eef1f5"
font                     = "sans serif"

[server]
headless = true
