[theme]
base                   = "dark"
primaryColor           = "#00FF87"
backgroundColor        = "#0e0e18"
secondaryBackgroundColor = "#16213e"
textColor              = "#e2e2e2"
font                   = "sans serif"

[server]
headless = true
